config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'recipes/index', to: 'recipes#public'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'recipes#public'
  resources :users do
    resources :recipes, except: :update do
      resources :recipe_foods
    end
  end
  resources :shopping_list
  resources :foods, except: :update
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy
  validates :name, :preparation_time, :cooking_time, :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @user = current_user
    @recipes = current_user.recipes.includes(:user).order(created_at: :desc)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe_foods = @recipe.recipe_foods
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  def public
    @public_recipes = Recipe.includes([:user], [:recipe_foods]).where(public: true).order(created_at: :desc)
    @public_recipes.each do |recipe|
      recipe.recipe_foods.all.includes([:food]).sort_by { |recipe_foods| recipe_foods.food.name }
    end
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = params[:user_id]

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to user_recipes_path(@recipe), notice: 'Recipe was successfully created. ✅' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to user_recipes_path(@recipe), notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(url:  user_recipes_path, model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <h1>
    <%= recipe.name %>
  </h1>
  <div class="recipe-detail-info">
    <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

<p class="switch-text">Public
  <label class="switch">
  <% if recipe.public == true  %>
  <input type="checkbox" checked>
  <%end%>
  <span class="slider round"></span>
</label>
</p>
  </div>


  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", recipes_index_path %> |
  <%= link_to "Back to recipes", recipes_index_path %>
</div>

app/views/recipes/index.html.erb
<%= stylesheet_link_tag "recipes_index.css" %>

<h1><%=@user.name %> Recipes List</h1>

<div id="recipes">
  <% if @recipes.empty? %>
     <h3>There are no recipes to display for this user. Please add a recipe.</h3>
  <% end %>
  <% @recipes.each do |recipe| %>
    <div class="recipes-container">
    <div class="recipes-card">
    <div class="recipe-informations">
    <h3><%= link_to recipe.name, user_recipe_path(id: recipe.id, user_id: recipe.user.id), class: "recipes-title" %></h3>
    <% if can? :manage, recipe %>
      <%= button_to "Delete" , user_recipe_path(recipe.user, recipe.id), method: :delete %>
    <% end %>
    </div>
    <p class="recipes-description"><%= recipe.description %></p>
    </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
   <%= link_to "Back to recipes",  recipes_index_path %>
</div>

app/views/recipes/public.html.erb
<div class="wrapper">

  <h2>Public Recipe List</h2>
  <% @public_recipes.each do |recipe| %>
    <div>
      <div>
        <h3>
          <%= link_to recipe.name, user_recipe_path(id: recipe.id, user_id: recipe.user.id) %>
        </h3>
        <h5> By:<span><%= recipe.user.name %></h5></span> 
        </div>
       <div>
        <h5>Total foods: <%= recipe.recipe_foods.length %> </h5>
        <% sum = 0 %>
        <h5>Total price : $ <% recipe.recipe_foods.each do |food| %>
        <% sum += food.food.price %>
        <% end %>
        <%= sum %></h5>
      </div>
      <div class="d-btn">
        <% if can? :manage, recipe %>
          <%= button_to "Delete" , user_recipe_path(recipe.user, recipe.id), method: :delete %>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @public_recipes.empty? %>
    <h1>There are no public recipes to show</h1>
  <% end %>
</div>

app/views/recipes/show.html.erb
<%= stylesheet_link_tag "recipe_show.css" %>

<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div class="recipe-detail-menu">
<%= link_to "Add ingredients",  new_user_recipe_recipe_food_path(recipe_id: @recipe) %>
<%= link_to "Generate Shopping List", shopping_list_index_path%>
</div>
<hr>
<div id="recipe_foods">
<table>
    <th>
      <p>
      <strong>Food</strong>
      </p>
    </th>
    <th>
      <p>
    <strong>Quantity</strong>
      </p>
    </th>
    <th>
      <p>
      <strong>Value</strong>
      </p>
    </th>
    <th>
      <p>
      <strong>Actions</strong>
      </p>
    </th>
  <% @recipe_foods.each do |recipe_food| %>
      <tr>
      <td>
      <%=  recipe_food.food.name %>
      </td>
      <td>
      <%= recipe_food.quantity%>
      </td>
      <td>
      $<%= recipe_food.food.price*recipe_food.quantity %>
      </td>

      <td>
      <% if can? :manage, @recipe %>
      <%= button_to "Delete" , user_recipe_path(@recipe.user, @recipe.id), method: :delete %>
      <% end %>
      </td>
      </tr>
  <% end %>
  </table>
</div>