config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'recipes/index', to: 'recipes#public'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'recipes#public'
  resources :users do
    resources :recipes, except: :update do
      resources :recipe_foods
    end
  end
  resources :shopping_list
  resources :foods, except: :update
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<html lang="<%= I18n.locale %>">
<html>
  <head>
    <title>RecipeApp</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="d-flex justify-content-between align-items-center">
      <nav role="navigation">
        <div id="menuToggle">
          <input type="checkbox" />
          <span></span>
          <span></span>
          <span></span>
          <ul id="menu">
            <% if user_signed_in? %>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <li><%= link_to  "Recipes List",  user_recipes_path(current_user.id) %></li>
              <li> <%= link_to  "Food List", foods_url %></li>
              <li> <%= link_to  "Shopping List", shopping_list_index_path	 %></li>
              <li> <%= link_to "Public Recipes", recipes_index_path %></li>
              <li> <%= link_to "Add Recipe", new_user_recipe_path(user_id: current_user.id) %></li>
              <li> <%= link_to "Add Food", new_food_path %></li>
            <% else %>
              <li><%= link_to  "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login in", new_user_session_path %></li>
              <li> <%= link_to "Public Recipes", recipes_index_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
      <h1 class="text-center">
        RecipeApp
      </h1>
    </header>
    <div class="main-wrapper">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>